# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort
        name: Sort imports with isort
        types: [python]
        # To keep consistent with the global isort skip config defined in .flake8
        exclude: ^build/.*$|^.tox/.*$|^venv/.*$
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused imports and expand star-imports
        language: system
        entry: "./scripts/ci/pre_commit/pre_commit_autoflake.sh"
        files: \.py$
        pass_filenames: true
      - id: flake8
        name: Run flake8
        language: system
        entry: "./scripts/ci/pre_commit/pre_commit_flake8.sh"
        files: \.py$
        pass_filenames: true
